---
#plugin coded by platinumgamesdevs we do custom plugins join our discord here https://discord.gg/bQkfnM6
? 'ENTITY ID (GO HERE FOR A LIST OF ENTITY IDs: https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/entity/EntityIds.php)'
: - - ITEM ID
    - DAMAGE
    - COUNT
  - - ITEM ID
    - DAMAGE
    - COUNT
12:
- - 302
  - 0
  - 16
- - 339
  - 0
  - 24
...
#adding percent drop to each itemid and how many of drop item soon
